version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rushimehta71@
      MYSQL_DATABASE: GroceryData
    ports:
      - "3307:3306"  # Changed from 3306 to 3307 to avoid conflicts
    networks:
      - grocery-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: grocery-app
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306  # Internal MySQL container port (unchanged)
    ports:
      - "8080:8080"
    networks:
      - grocery-network

networks:
  grocery-network:

volumes:
  mysql-data: